const actionTypes = {
  // Authentication Actions
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  SET_USER_ROLE: 'SET_USER_ROLE',

  // Users Actions
  SET_USER: 'SET_USER',
  UPDATE_USER: 'UPDATE_USER',
  RESET_USER: 'RESET_USER',
  SET_USERS: 'SET_USERS',
  ADD_USER: 'ADD_USER',
  DELETE_USER: 'DELETE_USER',
  SET_ARE_USERS_FETCHED: 'SET_ARE_USERS_FETCHED',

  // Products Actions
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  SHOW_PRODUCTS_ERROR: 'SHOW_PRODUCTS_ERROR',
  HIDE_PRODUCTS_ERROR: 'HIDE_PRODUCTS_ERROR',

  // Categories Actions
  FETCH_CATEGORIES: 'FETCH_CATEGORIES',
  CREATE_CATEGORY: 'CREATE_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  SHOW_CATEGORY_ERROR: 'SHOW_CATEGORY_ERROR',
  HIDE_CATEGORY_ERROR: 'HIDE_CATEGORY_ERROR',

  SHOW_SUCCESS_MESSAGE: 'SHOW_SUCCESS_MESSAGE',
  HIDE_SUCCESS_MESSAGE: 'HIDE_SUCCESS_MESSAGE',
  SHOW_ERROR: 'SHOW_ERROR',
  HIDE_ERROR: 'HIDE_ERROR',
  SHOW_CONFIRMATION: 'SHOW_CONFIRMATION',
  HIDE_CONFIRMATION: 'HIDE_CONFIRMATION',

  LOAD: 'LOAD',
  STOP_LOADING: 'STOP_LOADING',
};

export default actionTypes;
