const actionTypes = {
  // Authentication Actions
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',

  // Users Actions
  SET_USER: 'SET_USER',
  RESET_USER: 'RESET_USER',
  UPDATE_USER: 'UPDATE_USER',
  SET_USERS: 'SET_USERS',
  CREATE_USER: 'CREATE_USER',
  DELETE_USER: 'DELETE_USER',
  SHOW_USERS_ERROR: 'SHOW_USERS_ERROR',
  HIDE_USERS_ERROR: 'HIDE_USERS_ERROR',

  // Products Actions
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  SHOW_PRODUCTS_ERROR: 'SHOW_PRODUCTS_ERROR',
  HIDE_PRODUCTS_ERROR: 'HIDE_PRODUCTS_ERROR',

  // Categories Actions
  SET_CATEGORIES: 'SET_CATEGORIES',
  CREATE_CATEGORY: 'CREATE_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  SHOW_CATEGORY_ERROR: 'SHOW_CATEGORY_ERROR',
  HIDE_CATEGORY_ERROR: 'HIDE_CATEGORY_ERROR',

  // Suppliers Actions
  SET_SUPPLIERS: 'SET_SUPPLIERS',
  CREATE_SUPPLIER: 'CREATE_SUPPLIER',
  UPDATE_SUPPLIER: 'UPDATE_SUPPLIER',
  DELETE_SUPPLIER: 'DELETE_SUPPLIER',
  SHOW_SUPPLIER_ERROR: 'SHOW_SUPPLIER_ERROR',
  HIDE_SUPPLIER_ERROR: 'HIDE_SUPPLIER_ERROR',

  SHOW_SUCCESS_MESSAGE: 'SHOW_SUCCESS_MESSAGE',
  HIDE_SUCCESS_MESSAGE: 'HIDE_SUCCESS_MESSAGE',
  SHOW_ERROR: 'SHOW_ERROR',
  HIDE_ERROR: 'HIDE_ERROR',
  SHOW_CONFIRMATION: 'SHOW_CONFIRMATION',
  HIDE_CONFIRMATION: 'HIDE_CONFIRMATION',

  LOAD: 'LOAD',
  STOP_LOADING: 'STOP_LOADING',
};

export default actionTypes;
